{
 "title": "Home",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values({__name__=\"up\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_filesystem_size{instance=~\"$host\",device=~\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - node_boot_time{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Load CPU",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu{instance=\"$host\",mode=\"idle\"}[2m])) * 100)"
    }
   ]
  },
  {
   "title": "Load AVG",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load5{instance=~\"$host\"} / count without (cpu, mode) (node_cpu{instance=~\"$host\", mode=\"system\"})"
    }
   ]
  },
  {
   "title": "Disk Free",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(node_filesystem_free{instance=~\"$host\",mountpoint=\"/\"} / node_filesystem_size{instance=~\"$host\",mountpoint=\"/\"})"
    }
   ]
  },
  {
   "title": "I/O Activity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_vmstat_pgpgin{instance=\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{instance=\"$host\"}[5m]) * 1024",
     "legendFormat": "Page in"
    },
    {
     "expr": "rate(node_vmstat_pgpgout{instance=\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{instance=\"$host\"}[5m]) * 1024",
     "legendFormat": "Page out"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "clamp_max((avg by (mode) ( (clamp_max(rate(node_cpu{instance=\"$host\",mode!=\"idle\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host\",mode!=\"idle\"}[5m]),1)) ))*100,100)",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "clamp_max(max by () (sum  by (cpu) ( (clamp_max(rate(node_cpu{instance=\"$host\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) ))*100,100)",
     "legendFormat": "Max Core Utilization"
    },
    {
     "expr": "node_load1{instance=\"$host\"}",
     "legendFormat": "Load 1m"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes{instance=~\"$host\", device!~\"lo|bond[0-9]|cbr[0-9]|veth.*\"}[5m]) > 0",
     "legendFormat": "{{device}} outbound"
    },
    {
     "expr": "irate(node_network_receive_bytes{instance=~\"$host\", device!~\"lo|bond[0-9]|cbr[0-9]|veth.*\"}[5m]) > 0",
     "legendFormat": "{{device}} intbound"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal{instance=~\"$host\"} - node_memory_MemFree{instance=~\"$host\"} - node_memory_Cached{instance=~\"$host\"} - node_memory_Buffers{instance=~\"$host\"} - node_memory_Slab{instance=~\"$host\"}\n",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers{instance=~\"$host\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached{instance=~\"$host\"} + node_memory_Slab{instance=~\"$host\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree{instance=~\"$host\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Swap Activity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_vmstat_pswpin{instance=\"$host\"}[$interval]) * 4096 or irate(node_vmstat_pswpin{instance=\"$host\"}[5m]) * 4096",
     "legendFormat": "Swap In (Reads)"
    },
    {
     "expr": "rate(node_vmstat_pswpout{instance=\"$host\"}[$interval]) * 4096 or irate(node_vmstat_pswpout{instance=\"$host\"}[5m]) * 4096",
     "legendFormat": "Swap Out (Writes)"
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - node_filesystem_free{instance=\"$host\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"} / node_filesystem_size{instance=\"$host\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  }
 ]
}