{
 "title": "Nginx",
 "description": "Shows stats built from the Prometheus Nginx plugin.",
 "tags": [ "nginx" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "role", "query": "label_values(role)" },
   { "name": "status", "label": "response_code", "query": "label_values(status)" }
  ]
 },
 "panels": [
  {
   "title": "HTTP Responses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_http_requests_total{role=~\"$role\",status=~\"$status\",host!=\"127.0.0.1\"}[5m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "HTTP Requests By Host",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_http_requests_total{role=~\"$role\",status=~\"$status\",host!=\"127.0.0.1\"}[5m])) by (alias,status)",
     "legendFormat": "{{status}} {{alias}}"
    }
   ]
  },
  {
   "title": "Apdex",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(rate(nginx_http_request_duration_seconds_bucket{role=\"$role\",host!=\"127.0.0.1\",le=\"0.01\"}[1m]))+sum(rate(nginx_http_request_duration_seconds_bucket{role=\"$role\",host!=\"127.0.0.1\",le=\"0.01\"}[1m]))) / 2 / sum(rate(nginx_http_request_duration_seconds_count{role=\"$role\",host!=\"127.0.0.1\"}[1m]))"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_http_request_duration_seconds_sum{role=\"$role\",host!=\"127.0.0.1\"}[1m])) / sum(rate(nginx_http_request_duration_seconds_count{role=\"$role\",host!=\"127.0.0.1\"}[1m]))",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "Response time by Host",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_http_request_duration_seconds_sum{role=\"$role\",host!=\"127.0.0.1\"}[1m])) by (alias) / sum(rate(nginx_http_request_duration_seconds_count{role=\"$role\",host!=\"127.0.0.1\"}[1m])) by (alias)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Hosts",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(sum(nginx_http_request_duration_seconds_count{host!=\"127.0.0.1\",role=\"$role\"}) by (alias))"
    }
   ]
  }
 ]
}