{
 "title": "Application",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "label_values({__name__=\"up\"}, instance)"
   },
   {
    "name": "timeRange",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(app_http_requests{status_code=~\"(2|3)..\",instance=~\"$host\",mall_id=~\"$mall_id\"}[1m])) > 0",
     "legendFormat": "200"
    },
    {
     "expr": "sum(irate(app_http_requests{status_code=~\"4..\",instance=~\"$host\",mall_id=~\"$mall_id\"}[1m])) > 0",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(irate(app_http_requests{status_code=~\"5..\",instance=~\"$host\",mall_id=~\"$mall_id\"}[1m])) > 0",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(irate(app_http_response_time{instance=~\"$host\",mall_id=~\"$mall_id\",status_code=~\"(2|3)..\"}[1m]))/sum(irate(app_http_requests{instance=~\"$host\",mall_id=~\"$mall_id\",status_code=~\"(2|3)..\"}[1m]))",
     "legendFormat": "200"
    },
    {
     "expr": "sum(irate(app_http_response_time{instance=~\"$host\",mall_id=~\"$mall_id\",status_code=~\"4..\"}[1m]))/sum(irate(app_http_requests{instance=~\"$host\",mall_id=~\"$mall_id\",status_code=~\"4..\"}[1m]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(irate(app_http_response_time{instance=~\"$host\",mall_id=~\"$mall_id\",status_code=~\"5..\"}[1m]))/sum(irate(app_http_requests{instance=~\"$host\",mall_id=~\"$mall_id\",status_code=~\"5..\"}[1m]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(app_http_requests{instance=~\"$host\",mall_id=~\"$mall_id\"}[1m]))"
    }
   ]
  },
  {
   "title": "RPM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(app_http_requests{instance=~\"$host\",mall_id=~\"$mall_id\"}[5m])) * 60"
    }
   ]
  },
  {
   "title": "Malls Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (increase(app_http_requests{instance=~\"$host\",mall_id=\"1\"}[$timeRange]))",
     "legendFormat": "Пл Красн"
    },
    {
     "expr": "sum (increase(app_http_requests{instance=~\"$host\",mall_id=\"2\"}[$timeRange]))",
     "legendFormat": "Пл Новок"
    },
    {
     "expr": "sum (increase(app_http_requests{instance=~\"$host\",mall_id=\"3\"}[$timeRange]))",
     "legendFormat": "Аура Новос"
    },
    {
     "expr": "sum (increase(app_http_requests{instance=~\"$host\",mall_id=\"4\"}[$timeRange]))",
     "legendFormat": "Пл Уфа"
    },
    {
     "expr": "sum (increase(app_http_requests{instance=~\"$host\",mall_id=\"5\",route!=\"metrics\"}[$timeRange]))",
     "legendFormat": "Лето Петерб"
    },
    {
     "expr": "sum (increase(app_http_requests{instance=~\"$host\",mall_id=\"5\",route=\"metrics\"}[$timeRange])) by (mall_id)",
     "legendFormat": "Metrics"
    }
   ]
  },
  {
   "title": "Top requests",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "topk(5, sum (increase(app_http_requests{instance=~\"$host\",mall_id=~\"$mall_id\"}[$timeRange])) by (route)) > 0"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "topk(5, sum (increase(app_http_requests{status_code=~\"(4|5)..\",instance=~\"$host\",mall_id=~\"$mall_id\"}[$timeRange])) by (route)) > 0"
    }
   ]
  },
  {
   "title": "Slow requests",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "targets": [
    {
     "expr": "topk(5,\n    sum (\n        sum(\n            increase(app_http_response_time{instance=~\"$host\",mall_id=~\"$mall_id\"}[$timeRange]) > 0\n        ) by (route) / sum(\n            increase(app_http_requests{instance=~\"$host\",mall_id=~\"$mall_id\"}[$timeRange]) > 0\n        ) by (route)\n    ) by (route)\n) / 1000"
    }
   ]
  }
 ]
}