{
 "title": "Postgres 2",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "label_values({__name__=\"up\"}, instance)"
   },
   { "name": "database", "label": "Database", "query": "label_values(datname)" }
  ]
 },
 "panels": [
  { "title": "Syntetic query time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Mean query time (by entire instance)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_mean_time{datname!~\"template.*\", datname!~\"postgres\", instance=~\"$host\"}[1m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Mean query time (by entire database)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_mean_time{datname!~\"template.*\", datname!~\"postgres\", instance=~\"$host\", datname=~\"$database\"}[1m])) by (datname)",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  { "title": "Syntetic queries count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Total queries count (1m rate) by entire instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(pg_stat_statements_calls{datname!~\"template.*\", datname!~\"postgres\", instance=~\"$host\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total queries count (1m rate) by database",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(pg_stat_statements_calls{datname!~\"template.*\", datname!~\"postgres\", instance=~\"$host\", datname=~\"$database\"}[1m])) by (datname)",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Database size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "pg_database_size{datname!~\"template.*\", datname!~\"postgres\", instance=~\"$host\", datname=~\"$database\"}/(1024*1024*1024)",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "TOP-20 Most called queries (10m rate)",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "topk(20, increase(pg_stat_statements_calls{datname!~\"template.*\", datname!~\"postgres\", instance=~\"$host\", datname=~\"$database\"}[10m]))"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "TOP-20 Most long-running queries (by mean_time, except backups)",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "topk(20, pg_stat_statements_mean_time{datname!~\"template.*\", datname!~\"postgres\", short_query!~\"COPY.*\", instance=~\"$host\", datname=~\"$database\"})"
    }
   ]
  }
 ]
}